import supabase from './db-client.js';
const validToken=Buffer.from('admin:admin123').toString('base64');const isAdmin=req=>req.headers['x-admin-auth']===validToken;
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, PUT, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, X-Admin-Auth');if(req.method==='OPTIONS')return res.status(204).end();try{
 if(req.method==='POST'){const {username,password}=req.body||{};if(username!=='admin'||password!=='admin123')return res.status(401).json({error:'Invalid administrator credentials.'});return res.status(200).json({token:validToken})}
 if(!isAdmin(req))return res.status(401).json({error:'Unauthorized administrator'});
 if(req.method==='GET'&&req.query.resource==='appointments'){let query=supabase.from('appointments').select('*').order('appointment_date',{ascending:false});if(req.query.date)query=query.eq('appointment_date',req.query.date);if(req.query.department)query=query.eq('department',req.query.department);if(req.query.doctor)query=query.eq('doctor',req.query.doctor);if(req.query.q){const q=req.query.q.replace(/[,()]/g,'');query=query.or(`patient_name.ilike.%${q}%,email.ilike.%${q}%`)}const {data,error}=await query;if(error)throw error;return res.status(200).json(data)}
 if(req.method==='GET'){const today=new Date().toISOString().split('T')[0];const [users,doctors,appointments,todayRows]=await Promise.all([supabase.from('user_profiles').select('id',{count:'exact',head:true}),supabase.from('doctors').select('id',{count:'exact',head:true}),supabase.from('appointments').select('status'),supabase.from('appointments').select('id',{count:'exact',head:true}).eq('appointment_date',today)]);for(const r of [users,doctors,appointments,todayRows])if(r.error)throw r.error;const rows=appointments.data||[];return res.status(200).json({totalUsers:users.count||0,totalDoctors:doctors.count||0,todayAppointments:todayRows.count||0,totalAppointments:rows.length,pending:rows.filter(x=>x.status==='Pending').length,completed:rows.filter(x=>x.status==='Completed').length,cancelled:rows.filter(x=>['Cancelled','Rejected'].includes(x.status)).length})}
 if(req.method==='PUT'){const {resource,id,status}=req.body||{};if(resource!=='appointment'||!['Approved','Rejected','Completed'].includes(status))return res.status(400).json({error:'Invalid update.'});const {data,error}=await supabase.from('appointments').update({status}).eq('id',id).select().single();if(error)throw error;return res.status(200).json(data)}
 return res.status(405).json({error:'Method not allowed'});
 }catch(err){console.error('Admin API:',err);return res.status(500).json({error:err.message})}}
