import supabase from './db-client.js';
const cors=res=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, DELETE, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization')};
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();try{
 const token=req.headers.authorization?.replace('Bearer ','');if(!token)return res.status(401).json({error:'Please sign in to continue.'});const {data:{user},error:authError}=await supabase.auth.getUser(token);if(authError||!user)return res.status(401).json({error:'Your session has expired. Please sign in again.'});
 if(req.method==='GET'){const {data,error}=await supabase.from('appointments').select('*').eq('user_id',user.id).order('appointment_date',{ascending:false});if(error)throw error;return res.status(200).json(data)}
 if(req.method==='POST'){const b=req.body||{};const required=['patient_name','age','gender','phone','email','department','doctor_id','appointment_date','appointment_time','problem'];if(required.some(k=>!b[k]))return res.status(400).json({error:'Please complete every required field.'});if(!/^\+?[0-9 ()-]{7,18}$/.test(b.phone))return res.status(400).json({error:'Enter a valid phone number.'});const chosen=new Date(`${b.appointment_date}T00:00:00`);const today=new Date();today.setHours(0,0,0,0);if(chosen<=today)return res.status(400).json({error:'Appointments must be booked for a future date.'});const {data:doctor,error:doctorError}=await supabase.from('doctors').select('*').eq('id',Number(b.doctor_id)).single();if(doctorError||!doctor)return res.status(400).json({error:'The selected doctor was not found.'});if(doctor.department!==b.department)return res.status(400).json({error:'The selected doctor does not belong to this department.'});const {data:duplicate,error:dupError}=await supabase.from('appointments').select('id').eq('doctor_id',doctor.id).eq('appointment_date',b.appointment_date).eq('appointment_time',b.appointment_time).in('status',['Pending','Approved']).limit(1);if(dupError)throw dupError;if(duplicate?.length)return res.status(409).json({error:'That time is already booked. Please choose another slot.'});const {data,error}=await supabase.from('appointments').insert({user_id:user.id,patient_name:b.patient_name.trim(),age:Number(b.age),gender:b.gender,phone:b.phone.trim(),email:b.email.trim().toLowerCase(),department:b.department,doctor_id:doctor.id,doctor:doctor.doctor_name,appointment_date:b.appointment_date,appointment_time:b.appointment_time,problem:b.problem.trim(),status:'Pending'}).select().single();if(error)throw error;return res.status(201).json(data)}
 if(req.method==='DELETE'){const {id}=req.body||{};const {data:found,error:findError}=await supabase.from('appointments').select('status').eq('id',id).eq('user_id',user.id).single();if(findError||!found)return res.status(404).json({error:'Appointment not found.'});if(['Completed','Cancelled','Rejected'].includes(found.status))return res.status(400).json({error:'This appointment can no longer be cancelled.'});const {data,error}=await supabase.from('appointments').update({status:'Cancelled'}).eq('id',id).eq('user_id',user.id).select().single();if(error)throw error;return res.status(200).json(data)}
 return res.status(405).json({error:'Method not allowed'});
 }catch(err){console.error('Appointments API:',err);return res.status(500).json({error:err.message})}}
